exports.SERVER_DATA = {
  "810540153294684192": {
    "swearFilterOn": false,
    "name": "Khancord",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coonnass",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "hell no",
      "hell yeah",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell",
      "istg",
      "fkn",
      "kill yourself",
      "fckn",
      "nims",
      "ywy=",
      "fuckk",
      "omfg",
      "omfgg",
      "omfggg",
      "omfgggg",
      "omfggggg",
      "omfgggggg",
      "omfggggggg",
      "fu-",
      "https://www.youtube.com/watch?v=1qanhh6shfw",
      "https://tenor.com/view/hungary-hungarian-sex-symbol-hungarian-uncle-at-motel-gif-15791437",
      "https://tenor.com/view/ass-on-fire-sitting-on-fire-on-fire-gif-12188540",
      "https://tenor.com/view/billy-loomis-scream-bloody-hands-lick-blood-gif-15475777",
      "https://tenor.com/view/nacho-libre-jack-black-nacho-squeeze-butt-gif-4867990",
      "https://tenor.com/view/giraffe-give-birth-giving-birth-gif-13099492",
      "dumbass",
      "dumbfucker",
      "dumbbitch",
      "rape",
      "raped",
      "raping",
      "horny",
      "iesbian",
      "shi-",
      "mao",
      "lma",
      "sexism",
      "transexual",
      "raceist",
      "shi",
      "stripper",
      "cox",
      "meth",
      "femboy",
      "homophobe",
      "femboi",
      "goddamn",
      "motherfuckers",
      "dickfaces",
      "men"
    ],
    "busy": false,
    "logChannel": "928696139191046227"
  },
  "885353191317839922": {
    "swearFilterOn": true,
    "name": "SPARTA",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕"
    ]
  },
  "806054240824066049": {
    "name": "SJA/STMP Game Dev + hangout",
    "prefix": "?",
    "swearFilterOn": true,
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell",
      "hay"
    ],
    "logChannel": ""
  },
  "959041037693779988": {
    "name": "KA Game Development",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell"
    ],
    "swearFilterOn": false,
    "logChannel": ""
  },
  "959592129871626240": {
    "name": "Kestron Debugging",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "hell no",
      "hell yeah",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell",
      "testword"
    ],
    "swearFilterOn": true,
    "logChannel": ""
  }
}
