exports.SERVER_DATA = {
  "810540153294684192": {
    "swearFilterOn": true,
    "name": "Khancord",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell",
      "lgbtq",
      "gay",
      "lesbian",
      "bi",
      "bisexual",
      "asexual",
      "femboi",
      "femboy",
      "trans",
      "transgender",
      "lgbtqia",
      "lgbt",
      "lgbtqi",
      "lgbtg",
      "homophobic",
      "homophobe",
      "istg",
      "femboys",
      "shut up",
      "fkn",
      "kill yourself",
      "fckn",
      "<@!766834775473913916>",
      "vexy",
      "dum",
      "nim",
      "nims",
      "scratch"
    ],
    "busy": false
  },
  "885353191317839922": {
    "swearFilterOn": true,
    "name": "SPARTA",
    "prefix": "?",
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕"
    ]
  },
  "806054240824066049": {
    "name": "SJA/STMP Game Dev + hangout",
    "prefix": "?",
    "swearFilterOn": true,
    "bannedWords": [
      "anal",
      "anus",
      "arse",
      "ass",
      "ass fuck",
      "ass hole",
      "assfucker",
      "asshole",
      "assshole",
      "bastard",
      "bitch",
      "black cock",
      "bloody hell",
      "boner",
      "boobies",
      "boob",
      "boobs",
      "boong",
      "butt hole",
      "cock",
      "cockfucker",
      "cocksuck",
      "cocksucker",
      "condom",
      "coon",
      "coonnass",
      "crap",
      "cum",
      "cunt",
      "cyberfuck",
      "damm",
      "dammm",
      "damn",
      "deez nut",
      "dick",
      "douche",
      "dummy",
      "erect",
      "erection",
      "erotic",
      "escort",
      "fag",
      "faggot",
      "fuck",
      "fuck off",
      "fuck you",
      "fuckass",
      "fuckhole",
      "god damn",
      "gook",
      "the hell",
      "helll",
      "hell no",
      "homoerotic",
      "hore",
      "jerk off",
      "jerked off",
      "jerking off",
      "mother fucker",
      "motherfuck",
      "motherfucker",
      "negro",
      "nigga",
      "nigger",
      "nudes",
      "orgasim",
      "orgasm",
      "penis",
      "penisfucker",
      "pervert",
      "piss",
      "piss off",
      "porn",
      "porno",
      "pornography",
      "pornstar",
      "pussy",
      "retard",
      "sadist",
      "sex",
      "sexy",
      "shit",
      "shithole",
      "slut",
      "son of a bitch",
      "sperm",
      "testicle",
      "tits",
      "vagina",
      "viagra",
      "whore",
      "lmfao",
      "stfu",
      "ong",
      "🖕",
      "on god",
      "go to hell"
    ]
  }
}